name: GitHub Actions Demo
on:
  push:
    paths:
      - '.github/workflows/**'
    branches:
      - 'main'
  workflow_dispatch:

env:
  PRIVATE_KEY: 'id_rsa'
  LARGE_SECRET_PASSPHRASE: ${{ secrets.LARGE_SECRET_PASSPHRASE }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  Pull-repository-on-server:
    runs-on: ubuntu-latest
#    strategy:
#      matrix:
#        remote_host: [52.59.61.136, 35.158.68.117]

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: docker test
        run: |
          docker run hello-world
          docker ps
      - name: test bash script
        run: |
          count=0

          while [ $count -le 30 ];
          do
          	echo $count

          	containers=$(docker ps -q | wc -l)

          	if [ $containers -gt 0 ]
          		then
          			sleep 1m
          		else
          			break
          	fi
          	((count++))
          done
        shell: bash
#      - name: install ansible
#        run: |
#          sudo apt update && \
#          sudo apt install software-properties-common && \
#          sudo add-apt-repository --yes --update ppa:ansible/ansible && \
#          sudo apt install ansible
#          export ANSIBLE_CONFIG=ansible.cfg && \
#          echo "${{ secrets.ID_RSA }}" > ${{ env.PRIVATE_KEY }} && \
#          chmod 600 ${{ env.PRIVATE_KEY }} && \
#          echo `git rev-parse --show-toplevel`
#          ansible-playbook -vvv -i "${{ matrix.remote_host }}," -u ubuntu --private-key "`git rev-parse --show-toplevel`/${{ env.PRIVATE_KEY }}" genesis.yaml && \
#          rm ${{ env.PRIVATE_KEY }}


#      - name: Slack Notification
#        uses: 8398a7/action-slack@v3
#        with:
#          icon_emoji: ':octocat:'
#          status: ${{ job.status }}
#          fields: repo,author,eventName,workflow,job
#        env:
#          SLACK_WEBHOOK_URL: ${{secrets.SLACK_WEBHOOK_URL}}
#          MATRIX_CONTEXT: ${{ toJson(matrix) }}
#        if: always()


