name: GitHub Actions Demo
on:
  push:
    paths:
      - '.github/workflows/*'
    branches:
      - 'main'
env:
  PRIVATE_KEY: ${{ secrets.ID_RSA }}
  LARGE_SECRET_PASSPHRASE: ${{ secrets.LARGE_SECRET_PASSPHRASE }}

jobs:
  Pull-repository-on-server:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        remote_host: [35.156.11.26, 3.127.22.237]

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - uses: addnab/docker-run-action@v3
        with:
          image: ansible/ansible-runner:1
          options: -v ${{ github.workspace }}:/work
          run: |
            export ANSIBLE_CONFIG=/work/ansible.cfg && \
            echo "${{ secrets.ID_RSA }}" > /work/id_rsa && \
            chmod 600 /work/id_rsa && \
            ansible-playbook -v -i "${{ matrix.remote_host }}," -u ubuntu --private-key "/work/id_rsa" /work/genesis.yaml && \
            rm /work/id_rsa

      - name: Slack Notification
        uses: 8398a7/action-slack@v3
        with:
          status: custom
          custom_payload: |
            {
              "attachments": [
                {
                  "title": "Allure Report URL:",
                  "color": "${{job.status}}" === "success" ? "good" : "${{job.status}}" === "failure" ? "danger" : "warning",
                  "text": "${{steps.allure-report.outputs.report-url}}"
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{secrets.SLACK_WEBHOOK_URL}}
        if: always()


