name: GitHub Actions Demo
on:
  push:
    paths:
      - '.github/workflows/**'
    branches:
      - 'main'
env:
  PRIVATE_KEY: ${{ secrets.ID_RSA }}
  LARGE_SECRET_PASSPHRASE: ${{ secrets.LARGE_SECRET_PASSPHRASE }}

jobs:
  Pull-repository-on-server:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        remote_host: [52.59.61.136, 35.158.68.117]

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: install ansible
        run: |
          sudo apt update
          sudo apt install software-properties-common
          sudo add-apt-repository --yes --update ppa:ansible/ansible
          sudo apt install ansible
          export ANSIBLE_CONFIG=ansible.cfg && \
          echo "${{ secrets.ID_RSA }}" > id_rsa && \
          chmod 600 id_rsa && \
          ansible-playbook -v -i "${{ matrix.remote_host }}," -u ubuntu --private-key "id_rsa" genesis.yaml && \
          rm id_rsa


#      - name: Slack Notification
#        uses: 8398a7/action-slack@v3
#        with:
#          icon_emoji: ':octocat:'
#          status: ${{ job.status }}
#          fields: repo,author,eventName,workflow,job
#        env:
#          SLACK_WEBHOOK_URL: ${{secrets.SLACK_WEBHOOK_URL}}
#          MATRIX_CONTEXT: ${{ toJson(matrix) }}
#        if: always()


