name: Auto deploy to AWS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
#       - uses: actions/checkout@v1
#       - name: Execute Ansible Playbook
#         run: |
#           sudo apt install ansible &&
#           ansible-playbook -v \
#           -e aws_access_key=${{ secrets.aws_access_key }} \
#           -e aws_secret_key=${{ secrets.aws_secret_key }} \
#           genesis.yaml
        - name: test workflow commands
          run: echo '::set-output name=fruits::apple'
        - name: Outpur results 
          run: echo "It is a ${{ steps.outputs.fruits }}"
