name: GitHub Actions Demo
on:
  push:
    branches:
      - 'main'
#  pull_request:
#    branches:
#      - 'main'
#    types:
#      - synchronize
jobs:
  Pull-repository-on-server:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@main
        env:
            SSH_PRIVATE_KEY: ${{ secrets.KEY }}
            ARGS: "-avzr --delete"
            SOURCE: "*"
            REMOTE_HOST: ${{ secrets.HOST }}
            REMOTE_USER: ${{ secrets.USERNAME }}
            TARGET: code
            EXCLUDE: ".git, .github"
