name: Auto deploy to AWS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Install Ansible
      - uses: actions/checkout@v2
      - run: sudo apt update && sudo apt -y install ansible
      - run: ls -la
      - name: Run playbook
      - run: ansible-playbook genesis.yaml




