name: Auto deploy to AWS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Run playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          # Required, playbook filepath
          playbook: genesis.yml
          # Optional, additional flags to pass to ansible-playbook
          options: |
            --verbose
            -e aws_access_key=aws_access_key
            -e aws_secret_key=aws_secret_key

