name: GitHub Actions Demo
on:
  push:
    paths:
      - '.github/workflows/*'
    branches:
      - 'main'
env:
  PRIVATE_KEY: ${{ secrets.ID_RSA }}
  LARGE_SECRET_PASSPHRASE: ${{ secrets.LARGE_SECRET_PASSPHRASE }}

jobs:
  Pull-repository-on-server:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        remote_host: [35.156.11.26, 3.127.22.237]

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - uses: addnab/docker-run-action@v3
        with:
          image: ansible/ansible-runner:1
          options: -v ${{ github.workspace }}:/work
          run: |
            export ANSIBLE_CONFIG=/work/ansible.cfg && \
            echo "${{ secrets.ID_RSA }}" > /work/id_rsa && \
            chmod 600 /work/id_rsa && \
            ansible-playbook -v -i "${{ matrix.remote_host }}," -u ubuntu --private-key "/work/id_rsa" /work/genesis.yaml && \
            rm /work/id_rsa

      - name: Slack Notification
        uses: 8398a7/action-slack@v3
        with:
          status: custom
          fields: workflow,job,commit,repo,ref,author,took
          custom_payload: |
            {
              attachments: [{
                color: '${{ job.status }}' === 'success' ? 'good' : '${{ job.status }}' === 'failure' ? 'danger' : 'warning',
                text: `${process.env.AS_WORKFLOW}\n${process.env.AS_JOB} (${process.env.AS_COMMIT}) of ${process.env.AS_REPO}@${process.env.AS_REF} by ${process.env.AS_AUTHOR} ${{ job.status }} in ${process.env.AS_TOOK}`,
              }]
            }
        env:
          SLACK_WEBHOOK_URL: ${{secrets.SLACK_WEBHOOK_URL}}
        if: always()


