name: Auto deploy to AWS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      
      - name: Execute Ansible Playbook
      # You may pin to the exact commit or the version.
      # uses: saubermacherag/ansible-playbook-docker-action@6504ab82647581a928477ecb9c6d52f11fc6843f
        uses: saubermacherag/ansible-playbook-docker-action@v1.4
        with:
          # Name of the playbook in your workspace.
          playbookName: genesis.yaml 
          # Name of the inventory file to use.
          #inventoryFile: # optional
          # name of the requirements file to use.
          #requirementsFile: # optional
          # If you use private github repositories in your requirements file you need to set galaxyGithubUser and galaxyGithub token.
          #galaxyGithubUser: # optional
          # Token to access git source of roles to download. Only needed for private git sources. Github Account needs to be linked to Ansible Galaxy.
          #galaxyGithubToken: # optional
          # If inventoryFile is set you can also specify a custom roles path to install your required roles in.
          #rolesPath: # optional
          # Keyfile to use for host connections.
          #keyFile: # optional
          # Vault Password to decrypt keyFile.
          #keyFileVaultPass: # optional
          # String containing all extraVars which you want to be injected into the run.
          #extraVars: # optional
          # File containing extra vars.
          #extraFile: # optional
          # Choose one of 4 verbosity levels. See Ansible documentation for details.
          verbosity: true



