name: GitHub Actions Demo
on:
  push:
    branches:
      - 'main'

jobs:
  Pull-repository-on-server:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - remote_host: 3.67.72.253
            remote_user: ec2-user
            target: code

          - remote_host: 18.197.124.148
            remote_user: ec2-user
            target: test

    steps:
      - name: Run SSH command
        uses: garygrossgarten/github-action-ssh@v0.6.3
        with:
          command: tar -zcvf /tmp/${{ matrix.target }}.tar.gz ${{ matrix.target }}/app
          host: ${{ matrix.remote_host }}
          username: ${{ matrix.remote_user }}
          privateKey: ${{ secrets.KEY }}

      - name: checkout
        uses: actions/checkout@v1

      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@main
        env:
            SSH_PRIVATE_KEY: ${{ secrets.KEY }}
            ARGS: "-avzr --delete"
            SOURCE: "."
            REMOTE_HOST: ${{ matrix.remote_host }}
            REMOTE_USER: ${{ matrix.remote_user }}
            TARGET: ${{ matrix.target }}
            EXCLUDE: ".git, .github"

