name: GitHub Actions Demo
on:
  push:
    paths:
      - 'inventory/host'
    branches:
      - 'main'
env:
  PRIVATE_KEY: ${{ secrets.ID_RSA }}
  LARGE_SECRET_PASSPHRASE: ${{ secrets.LARGE_SECRET_PASSPHRASE }}
jobs:

  Pull-repository-on-server:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        remote_host: [35.156.11.26, 3.127.22.237]
#        include:
#          - remote_host: 54.93.244.229
#            remote_user: ec2-user
#            target: code
#
#          - remote_host: 3.66.213.176
#            remote_user: ec2-user
#            target: test

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - uses: addnab/docker-run-action@v3
        with:
          image: ansible/ansible-runner:1
          options: -v ${{ github.workspace }}:/work
          run: |
            ls -la
            ls -la /work/
            export ANSIBLE_CONFIG=/work/ansible.cfg
            gpg --quiet --batch --yes --decrypt --passphrase="$LARGE_SECRET_PASSPHRASE" --output /work/id_rsa id_rsa.gpg
            ansible-playbook -vvv -i "${{ matrix.remote_host }}," -u ubuntu --private-key "/work/id_rsa" /work/genesis.yaml
